// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
)

const getActiveUsersInPeriod = `-- name: GetActiveUsersInPeriod :one
SELECT COUNT(DISTINCT pubkey) AS active_users
FROM blob_references
WHERE created >= $1 AND created < $2
`

type GetActiveUsersInPeriodParams struct {
	Created   int64
	Created_2 int64
}

// Count users with activity (uploads) in a time period
func (q *Queries) GetActiveUsersInPeriod(ctx context.Context, arg GetActiveUsersInPeriodParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveUsersInPeriod, arg.Created, arg.Created_2)
	var active_users int64
	err := row.Scan(&active_users)
	return active_users, err
}

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT
    CASE
        WHEN type LIKE 'image/%' THEN 'image'
        WHEN type LIKE 'video/%' THEN 'video'
        WHEN type LIKE 'audio/%' THEN 'audio'
        WHEN type LIKE 'text/%' THEN 'text'
        WHEN type LIKE 'application/pdf' THEN 'document'
        WHEN type LIKE 'application/%zip%' OR type LIKE 'application/%tar%' OR type LIKE 'application/%gzip%' THEN 'archive'
        ELSE 'other'
    END AS category,
    COUNT(*) AS blob_count,
    COALESCE(SUM(size), 0) AS total_size
FROM blobs
GROUP BY category
ORDER BY total_size DESC
`

type GetCategoryBreakdownRow struct {
	Category  string
	BlobCount int64
	TotalSize interface{}
}

// Get blob counts by content category (derived from MIME type prefix)
func (q *Queries) GetCategoryBreakdown(ctx context.Context) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryBreakdownRow
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(&i.Category, &i.BlobCount, &i.TotalSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContentTypeBreakdown = `-- name: GetContentTypeBreakdown :many
SELECT
    type AS mime_type,
    COUNT(*) AS blob_count,
    COALESCE(SUM(size), 0) AS total_size
FROM blobs
GROUP BY type
ORDER BY total_size DESC
LIMIT $1
`

type GetContentTypeBreakdownRow struct {
	MimeType  string
	BlobCount int64
	TotalSize interface{}
}

// Get blob counts and sizes by MIME type
func (q *Queries) GetContentTypeBreakdown(ctx context.Context, limit int32) ([]GetContentTypeBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getContentTypeBreakdown, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContentTypeBreakdownRow
	for rows.Next() {
		var i GetContentTypeBreakdownRow
		if err := rows.Scan(&i.MimeType, &i.BlobCount, &i.TotalSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeduplicationStats = `-- name: GetDeduplicationStats :one
SELECT
    (SELECT COUNT(*) FROM blobs) AS unique_blobs,
    (SELECT COUNT(*) FROM blob_references) AS total_references,
    (SELECT COALESCE(SUM(size), 0) FROM blobs) AS actual_storage,
    (SELECT COALESCE(SUM(b.size), 0) FROM blob_references br JOIN blobs b ON br.hash = b.hash) AS logical_storage
`

type GetDeduplicationStatsRow struct {
	UniqueBlobs     int64
	TotalReferences int64
	ActualStorage   interface{}
	LogicalStorage  interface{}
}

// Get deduplication statistics
func (q *Queries) GetDeduplicationStats(ctx context.Context) (GetDeduplicationStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDeduplicationStats)
	var i GetDeduplicationStatsRow
	err := row.Scan(
		&i.UniqueBlobs,
		&i.TotalReferences,
		&i.ActualStorage,
		&i.LogicalStorage,
	)
	return i, err
}

const getEncryptionStats = `-- name: GetEncryptionStats :one
SELECT
    COUNT(*) AS total_blobs,
    COUNT(CASE WHEN encryption_mode = 'server' THEN 1 END) AS server_encrypted,
    COUNT(CASE WHEN encryption_mode = 'e2e' THEN 1 END) AS e2e_encrypted,
    COUNT(CASE WHEN encryption_mode = 'none' OR encryption_mode = '' OR encryption_mode IS NULL THEN 1 END) AS unencrypted
FROM blobs
`

type GetEncryptionStatsRow struct {
	TotalBlobs      int64
	ServerEncrypted int64
	E2eEncrypted    int64
	Unencrypted     int64
}

// Get encryption usage statistics
func (q *Queries) GetEncryptionStats(ctx context.Context) (GetEncryptionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getEncryptionStats)
	var i GetEncryptionStatsRow
	err := row.Scan(
		&i.TotalBlobs,
		&i.ServerEncrypted,
		&i.E2eEncrypted,
		&i.Unencrypted,
	)
	return i, err
}

const getNewUsersPerDay = `-- name: GetNewUsersPerDay :many
SELECT
    (created_at / 86400) * 86400 AS bucket_timestamp,
    COUNT(*) AS user_count
FROM users
WHERE created_at >= $1 AND created_at < $2
GROUP BY bucket_timestamp
ORDER BY bucket_timestamp ASC
`

type GetNewUsersPerDayParams struct {
	CreatedAt   int64
	CreatedAt_2 int64
}

type GetNewUsersPerDayRow struct {
	BucketTimestamp int32
	UserCount       int64
}

// Get new user registrations grouped by day
func (q *Queries) GetNewUsersPerDay(ctx context.Context, arg GetNewUsersPerDayParams) ([]GetNewUsersPerDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getNewUsersPerDay, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewUsersPerDayRow
	for rows.Next() {
		var i GetNewUsersPerDayRow
		if err := rows.Scan(&i.BucketTimestamp, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivity = `-- name: GetRecentActivity :one
SELECT
    (SELECT COUNT(*) FROM blobs b WHERE b.created >= $1) AS uploads,
    (SELECT COUNT(*) FROM blob_references br WHERE br.created >= $1) AS references,
    (SELECT COALESCE(SUM(b2.size), 0) FROM blobs b2 WHERE b2.created >= $1) AS bytes_uploaded,
    (SELECT COUNT(*) FROM users u WHERE u.created_at >= $1) AS new_users
`

type GetRecentActivityRow struct {
	Uploads       int64
	References    int64
	BytesUploaded interface{}
	NewUsers      int64
}

// Get activity counts for the last N seconds
func (q *Queries) GetRecentActivity(ctx context.Context, created int64) (GetRecentActivityRow, error) {
	row := q.db.QueryRowContext(ctx, getRecentActivity, created)
	var i GetRecentActivityRow
	err := row.Scan(
		&i.Uploads,
		&i.References,
		&i.BytesUploaded,
		&i.NewUsers,
	)
	return i, err
}

const getReferencesPerDay = `-- name: GetReferencesPerDay :many
SELECT
    (created / 86400) * 86400 AS bucket_timestamp,
    COUNT(*) AS reference_count
FROM blob_references
WHERE created >= $1 AND created < $2
GROUP BY bucket_timestamp
ORDER BY bucket_timestamp ASC
`

type GetReferencesPerDayParams struct {
	Created   int64
	Created_2 int64
}

type GetReferencesPerDayRow struct {
	BucketTimestamp int32
	ReferenceCount  int64
}

// Get blob reference (user uploads) counts grouped by day
func (q *Queries) GetReferencesPerDay(ctx context.Context, arg GetReferencesPerDayParams) ([]GetReferencesPerDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getReferencesPerDay, arg.Created, arg.Created_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReferencesPerDayRow
	for rows.Next() {
		var i GetReferencesPerDayRow
		if err := rows.Scan(&i.BucketTimestamp, &i.ReferenceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorageAtTime = `-- name: GetStorageAtTime :one
SELECT
    COALESCE(SUM(size), 0) AS total_bytes,
    COUNT(*) AS blob_count
FROM blobs
WHERE created < $1
`

type GetStorageAtTimeRow struct {
	TotalBytes interface{}
	BlobCount  int64
}

// Get total storage at a specific point in time
func (q *Queries) GetStorageAtTime(ctx context.Context, created int64) (GetStorageAtTimeRow, error) {
	row := q.db.QueryRowContext(ctx, getStorageAtTime, created)
	var i GetStorageAtTimeRow
	err := row.Scan(&i.TotalBytes, &i.BlobCount)
	return i, err
}

const getStorageGrowthDaily = `-- name: GetStorageGrowthDaily :many
WITH daily_additions AS (
    SELECT
        (created / 86400) * 86400 AS bucket_timestamp,
        COALESCE(SUM(size), 0) AS day_bytes,
        COUNT(*) AS day_blobs
    FROM blobs
    WHERE created >= $1 AND created < $2
    GROUP BY bucket_timestamp
)
SELECT
    bucket_timestamp,
    day_bytes,
    day_blobs,
    SUM(day_bytes) OVER (ORDER BY bucket_timestamp) AS cumulative_bytes,
    SUM(day_blobs) OVER (ORDER BY bucket_timestamp) AS cumulative_blobs
FROM daily_additions
ORDER BY bucket_timestamp ASC
`

type GetStorageGrowthDailyParams struct {
	Created   int64
	Created_2 int64
}

type GetStorageGrowthDailyRow struct {
	BucketTimestamp int32
	DayBytes        interface{}
	DayBlobs        int64
	CumulativeBytes int64
	CumulativeBlobs int64
}

// Get cumulative storage growth by day (for charts)
// Uses window function for running total
func (q *Queries) GetStorageGrowthDaily(ctx context.Context, arg GetStorageGrowthDailyParams) ([]GetStorageGrowthDailyRow, error) {
	rows, err := q.db.QueryContext(ctx, getStorageGrowthDaily, arg.Created, arg.Created_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStorageGrowthDailyRow
	for rows.Next() {
		var i GetStorageGrowthDailyRow
		if err := rows.Scan(
			&i.BucketTimestamp,
			&i.DayBytes,
			&i.DayBlobs,
			&i.CumulativeBytes,
			&i.CumulativeBlobs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopUsersByUsage = `-- name: GetTopUsersByUsage :many
SELECT
    u.pubkey,
    u.used_bytes,
    u.updated_at AS last_active,
    COALESCE(br_counts.blob_count, 0) AS blob_count
FROM users u
LEFT JOIN (
    SELECT pubkey, COUNT(*) AS blob_count
    FROM blob_references
    GROUP BY pubkey
) br_counts ON u.pubkey = br_counts.pubkey
WHERE u.used_bytes > 0
ORDER BY u.used_bytes DESC
LIMIT $1
`

type GetTopUsersByUsageRow struct {
	Pubkey     string
	UsedBytes  int64
	LastActive int64
	BlobCount  int64
}

// Get users with highest storage usage (using JOIN for efficiency)
func (q *Queries) GetTopUsersByUsage(ctx context.Context, limit int32) ([]GetTopUsersByUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopUsersByUsage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopUsersByUsageRow
	for rows.Next() {
		var i GetTopUsersByUsageRow
		if err := rows.Scan(
			&i.Pubkey,
			&i.UsedBytes,
			&i.LastActive,
			&i.BlobCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadsPerDay = `-- name: GetUploadsPerDay :many

SELECT
    (created / 86400) * 86400 AS bucket_timestamp,
    COUNT(*) AS upload_count,
    COALESCE(SUM(size), 0) AS total_bytes
FROM blobs
WHERE created >= $1 AND created < $2
GROUP BY bucket_timestamp
ORDER BY bucket_timestamp ASC
`

type GetUploadsPerDayParams struct {
	Created   int64
	Created_2 int64
}

type GetUploadsPerDayRow struct {
	BucketTimestamp int32
	UploadCount     int64
	TotalBytes      interface{}
}

// Analytics queries for dashboard metrics
// Get upload counts grouped by day within a time range
func (q *Queries) GetUploadsPerDay(ctx context.Context, arg GetUploadsPerDayParams) ([]GetUploadsPerDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getUploadsPerDay, arg.Created, arg.Created_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUploadsPerDayRow
	for rows.Next() {
		var i GetUploadsPerDayRow
		if err := rows.Scan(&i.BucketTimestamp, &i.UploadCount, &i.TotalBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUsageDistribution = `-- name: GetUserUsageDistribution :many
SELECT
    CASE
        WHEN used_bytes = 0 THEN 0
        WHEN used_bytes < 1048576 THEN 1048576  -- < 1MB
        WHEN used_bytes < 10485760 THEN 10485760  -- < 10MB
        WHEN used_bytes < 104857600 THEN 104857600  -- < 100MB
        WHEN used_bytes < 1073741824 THEN 1073741824  -- < 1GB
        ELSE 10737418240  -- >= 1GB (10GB bucket)
    END AS max_bytes,
    COUNT(*) AS user_count
FROM users
GROUP BY max_bytes
ORDER BY max_bytes ASC
`

type GetUserUsageDistributionRow struct {
	MaxBytes  float64
	UserCount int64
}

// Get user distribution by usage buckets
// Returns count of users in each storage tier
func (q *Queries) GetUserUsageDistribution(ctx context.Context) ([]GetUserUsageDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserUsageDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserUsageDistributionRow
	for rows.Next() {
		var i GetUserUsageDistributionRow
		if err := rows.Scan(&i.MaxBytes, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
