// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blob_references.sql

package db

import (
	"context"
)

const countBlobReferences = `-- name: CountBlobReferences :one
SELECT COUNT(*) as count
FROM blob_references
WHERE hash = $1
`

func (q *Queries) CountBlobReferences(ctx context.Context, hash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlobReferences, hash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlobReference = `-- name: CreateBlobReference :one
INSERT INTO blob_references (pubkey, hash, created)
VALUES ($1, $2, $3)
ON CONFLICT (pubkey, hash) DO NOTHING
RETURNING pubkey, hash, created
`

type CreateBlobReferenceParams struct {
	Pubkey  string
	Hash    string
	Created int64
}

func (q *Queries) CreateBlobReference(ctx context.Context, arg CreateBlobReferenceParams) (BlobReference, error) {
	row := q.db.QueryRowContext(ctx, createBlobReference, arg.Pubkey, arg.Hash, arg.Created)
	var i BlobReference
	err := row.Scan(&i.Pubkey, &i.Hash, &i.Created)
	return i, err
}

const deleteBlobReference = `-- name: DeleteBlobReference :exec
DELETE FROM blob_references
WHERE pubkey = $1 AND hash = $2
`

type DeleteBlobReferenceParams struct {
	Pubkey string
	Hash   string
}

func (q *Queries) DeleteBlobReference(ctx context.Context, arg DeleteBlobReferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlobReference, arg.Pubkey, arg.Hash)
	return err
}

const getBlobReference = `-- name: GetBlobReference :one
SELECT pubkey, hash, created
FROM blob_references
WHERE pubkey = $1 AND hash = $2
LIMIT 1
`

type GetBlobReferenceParams struct {
	Pubkey string
	Hash   string
}

func (q *Queries) GetBlobReference(ctx context.Context, arg GetBlobReferenceParams) (BlobReference, error) {
	row := q.db.QueryRowContext(ctx, getBlobReference, arg.Pubkey, arg.Hash)
	var i BlobReference
	err := row.Scan(&i.Pubkey, &i.Hash, &i.Created)
	return i, err
}

const getBlobReferencesByHash = `-- name: GetBlobReferencesByHash :many
SELECT pubkey, hash, created
FROM blob_references
WHERE hash = $1
`

func (q *Queries) GetBlobReferencesByHash(ctx context.Context, hash string) ([]BlobReference, error) {
	rows, err := q.db.QueryContext(ctx, getBlobReferencesByHash, hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlobReference
	for rows.Next() {
		var i BlobReference
		if err := rows.Scan(&i.Pubkey, &i.Hash, &i.Created); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlobReferencesByPubkey = `-- name: GetBlobReferencesByPubkey :many
SELECT pubkey, hash, created
FROM blob_references
WHERE pubkey = $1
`

func (q *Queries) GetBlobReferencesByPubkey(ctx context.Context, pubkey string) ([]BlobReference, error) {
	rows, err := q.db.QueryContext(ctx, getBlobReferencesByPubkey, pubkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlobReference
	for rows.Next() {
		var i BlobReference
		if err := rows.Scan(&i.Pubkey, &i.Hash, &i.Created); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasBlobReference = `-- name: HasBlobReference :one
SELECT EXISTS(
    SELECT 1 FROM blob_references
    WHERE pubkey = $1 AND hash = $2
) as exists
`

type HasBlobReferenceParams struct {
	Pubkey string
	Hash   string
}

func (q *Queries) HasBlobReference(ctx context.Context, arg HasBlobReferenceParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasBlobReference, arg.Pubkey, arg.Hash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
