// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocklist.sql

package db

import (
	"context"
)

const addToBlocklist = `-- name: AddToBlocklist :one
INSERT INTO blocklist (pubkey, reason, blocked_by, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (pubkey) DO UPDATE SET reason = excluded.reason, blocked_by = excluded.blocked_by
RETURNING pubkey, reason, blocked_by, created_at
`

type AddToBlocklistParams struct {
	Pubkey    string
	Reason    string
	BlockedBy string
	CreatedAt int64
}

func (q *Queries) AddToBlocklist(ctx context.Context, arg AddToBlocklistParams) (Blocklist, error) {
	row := q.db.QueryRowContext(ctx, addToBlocklist,
		arg.Pubkey,
		arg.Reason,
		arg.BlockedBy,
		arg.CreatedAt,
	)
	var i Blocklist
	err := row.Scan(
		&i.Pubkey,
		&i.Reason,
		&i.BlockedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getBlocklistCount = `-- name: GetBlocklistCount :one
SELECT COUNT(*) as count
FROM blocklist
`

func (q *Queries) GetBlocklistCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlocklistCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBlocklistEntry = `-- name: GetBlocklistEntry :one
SELECT pubkey, reason, blocked_by, created_at
FROM blocklist
WHERE pubkey = $1
LIMIT 1
`

func (q *Queries) GetBlocklistEntry(ctx context.Context, pubkey string) (Blocklist, error) {
	row := q.db.QueryRowContext(ctx, getBlocklistEntry, pubkey)
	var i Blocklist
	err := row.Scan(
		&i.Pubkey,
		&i.Reason,
		&i.BlockedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTransparencyStats = `-- name: GetTransparencyStats :one
SELECT id, total_reports, reports_actioned, reports_dismissed, blobs_removed, users_banned, last_updated
FROM transparency_stats
WHERE id = 1
`

func (q *Queries) GetTransparencyStats(ctx context.Context) (TransparencyStat, error) {
	row := q.db.QueryRowContext(ctx, getTransparencyStats)
	var i TransparencyStat
	err := row.Scan(
		&i.ID,
		&i.TotalReports,
		&i.ReportsActioned,
		&i.ReportsDismissed,
		&i.BlobsRemoved,
		&i.UsersBanned,
		&i.LastUpdated,
	)
	return i, err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS(
    SELECT 1 FROM blocklist WHERE pubkey = $1
) as is_blocked
`

func (q *Queries) IsBlocked(ctx context.Context, pubkey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBlocked, pubkey)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const listBlocklist = `-- name: ListBlocklist :many
SELECT pubkey, reason, blocked_by, created_at
FROM blocklist
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBlocklistParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBlocklist(ctx context.Context, arg ListBlocklistParams) ([]Blocklist, error) {
	rows, err := q.db.QueryContext(ctx, listBlocklist, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blocklist
	for rows.Next() {
		var i Blocklist
		if err := rows.Scan(
			&i.Pubkey,
			&i.Reason,
			&i.BlockedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromBlocklist = `-- name: RemoveFromBlocklist :exec
DELETE FROM blocklist
WHERE pubkey = $1
`

func (q *Queries) RemoveFromBlocklist(ctx context.Context, pubkey string) error {
	_, err := q.db.ExecContext(ctx, removeFromBlocklist, pubkey)
	return err
}

const updateTransparencyStats = `-- name: UpdateTransparencyStats :exec
UPDATE transparency_stats
SET total_reports = $1,
    reports_actioned = $2,
    reports_dismissed = $3,
    blobs_removed = $4,
    users_banned = $5,
    last_updated = $6
WHERE id = 1
`

type UpdateTransparencyStatsParams struct {
	TotalReports     int64
	ReportsActioned  int64
	ReportsDismissed int64
	BlobsRemoved     int64
	UsersBanned      int64
	LastUpdated      int64
}

func (q *Queries) UpdateTransparencyStats(ctx context.Context, arg UpdateTransparencyStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateTransparencyStats,
		arg.TotalReports,
		arg.ReportsActioned,
		arg.ReportsDismissed,
		arg.BlobsRemoved,
		arg.UsersBanned,
		arg.LastUpdated,
	)
	return err
}
