// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expiration.sql

package db

import (
	"context"
	"database/sql"
)

const clearBlobExpiration = `-- name: ClearBlobExpiration :exec
UPDATE blobs
SET expires_at = NULL
WHERE hash = $1
`

func (q *Queries) ClearBlobExpiration(ctx context.Context, hash string) error {
	_, err := q.db.ExecContext(ctx, clearBlobExpiration, hash)
	return err
}

const countExpiredBlobs = `-- name: CountExpiredBlobs :one
SELECT COUNT(*) as count
FROM blobs
WHERE expires_at IS NOT NULL
  AND expires_at <= $1
`

func (q *Queries) CountExpiredBlobs(ctx context.Context, expiresAt sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpiredBlobs, expiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpirationPolicy = `-- name: CreateExpirationPolicy :one
INSERT INTO expiration_policies (
    name, mime_prefix, ttl_seconds, max_size, pubkey, priority, enabled, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, mime_prefix, ttl_seconds, max_size, pubkey, priority, enabled, created_at, updated_at
`

type CreateExpirationPolicyParams struct {
	Name       string
	MimePrefix sql.NullString
	TtlSeconds int32
	MaxSize    sql.NullInt64
	Pubkey     sql.NullString
	Priority   int32
	Enabled    bool
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateExpirationPolicy(ctx context.Context, arg CreateExpirationPolicyParams) (ExpirationPolicy, error) {
	row := q.db.QueryRowContext(ctx, createExpirationPolicy,
		arg.Name,
		arg.MimePrefix,
		arg.TtlSeconds,
		arg.MaxSize,
		arg.Pubkey,
		arg.Priority,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ExpirationPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimePrefix,
		&i.TtlSeconds,
		&i.MaxSize,
		&i.Pubkey,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpirationPolicy = `-- name: DeleteExpirationPolicy :exec
DELETE FROM expiration_policies
WHERE id = $1
`

func (q *Queries) DeleteExpirationPolicy(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteExpirationPolicy, id)
	return err
}

const deleteExpiredBlobs = `-- name: DeleteExpiredBlobs :many
DELETE FROM blobs
WHERE expires_at IS NOT NULL
  AND expires_at <= $1
RETURNING hash
`

func (q *Queries) DeleteExpiredBlobs(ctx context.Context, expiresAt sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredBlobs, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var hash string
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpirationPolicies = `-- name: GetExpirationPolicies :many
SELECT id, name, mime_prefix, ttl_seconds, max_size, pubkey, priority, enabled, created_at, updated_at
FROM expiration_policies
WHERE enabled = TRUE
ORDER BY priority DESC
`

func (q *Queries) GetExpirationPolicies(ctx context.Context) ([]ExpirationPolicy, error) {
	rows, err := q.db.QueryContext(ctx, getExpirationPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpirationPolicy
	for rows.Next() {
		var i ExpirationPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimePrefix,
			&i.TtlSeconds,
			&i.MaxSize,
			&i.Pubkey,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpirationPolicy = `-- name: GetExpirationPolicy :one
SELECT id, name, mime_prefix, ttl_seconds, max_size, pubkey, priority, enabled, created_at, updated_at
FROM expiration_policies
WHERE id = $1
`

func (q *Queries) GetExpirationPolicy(ctx context.Context, id int32) (ExpirationPolicy, error) {
	row := q.db.QueryRowContext(ctx, getExpirationPolicy, id)
	var i ExpirationPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimePrefix,
		&i.TtlSeconds,
		&i.MaxSize,
		&i.Pubkey,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpiredBlobs = `-- name: GetExpiredBlobs :many
SELECT hash, pubkey, type, size, created
FROM blobs
WHERE expires_at IS NOT NULL
  AND expires_at <= $1
LIMIT $2
`

type GetExpiredBlobsParams struct {
	ExpiresAt sql.NullInt64
	Limit     int32
}

type GetExpiredBlobsRow struct {
	Hash    string
	Pubkey  string
	Type    string
	Size    int64
	Created int64
}

func (q *Queries) GetExpiredBlobs(ctx context.Context, arg GetExpiredBlobsParams) ([]GetExpiredBlobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredBlobs, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredBlobsRow
	for rows.Next() {
		var i GetExpiredBlobsRow
		if err := rows.Scan(
			&i.Hash,
			&i.Pubkey,
			&i.Type,
			&i.Size,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchingPolicy = `-- name: GetMatchingPolicy :one
SELECT id, name, mime_prefix, ttl_seconds, max_size, pubkey, priority, enabled, created_at, updated_at
FROM expiration_policies
WHERE enabled = TRUE
  AND (pubkey IS NULL OR pubkey = $1)
  AND (mime_prefix IS NULL OR $2 LIKE mime_prefix || '%')
  AND (max_size IS NULL OR $3 <= max_size)
ORDER BY priority DESC
LIMIT 1
`

type GetMatchingPolicyParams struct {
	Pubkey     sql.NullString
	MimePrefix sql.NullString
	MaxSize    sql.NullInt64
}

func (q *Queries) GetMatchingPolicy(ctx context.Context, arg GetMatchingPolicyParams) (ExpirationPolicy, error) {
	row := q.db.QueryRowContext(ctx, getMatchingPolicy, arg.Pubkey, arg.MimePrefix, arg.MaxSize)
	var i ExpirationPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimePrefix,
		&i.TtlSeconds,
		&i.MaxSize,
		&i.Pubkey,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setBlobExpiration = `-- name: SetBlobExpiration :exec
UPDATE blobs
SET expires_at = $2
WHERE hash = $1
`

type SetBlobExpirationParams struct {
	Hash      string
	ExpiresAt sql.NullInt64
}

func (q *Queries) SetBlobExpiration(ctx context.Context, arg SetBlobExpirationParams) error {
	_, err := q.db.ExecContext(ctx, setBlobExpiration, arg.Hash, arg.ExpiresAt)
	return err
}

const updateExpirationPolicy = `-- name: UpdateExpirationPolicy :exec
UPDATE expiration_policies
SET mime_prefix = $2,
    ttl_seconds = $3,
    max_size = $4,
    pubkey = $5,
    priority = $6,
    enabled = $7,
    updated_at = $8
WHERE id = $1
`

type UpdateExpirationPolicyParams struct {
	ID         int32
	MimePrefix sql.NullString
	TtlSeconds int32
	MaxSize    sql.NullInt64
	Pubkey     sql.NullString
	Priority   int32
	Enabled    bool
	UpdatedAt  int64
}

func (q *Queries) UpdateExpirationPolicy(ctx context.Context, arg UpdateExpirationPolicyParams) error {
	_, err := q.db.ExecContext(ctx, updateExpirationPolicy,
		arg.ID,
		arg.MimePrefix,
		arg.TtlSeconds,
		arg.MaxSize,
		arg.Pubkey,
		arg.Priority,
		arg.Enabled,
		arg.UpdatedAt,
	)
	return err
}
