// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: federation.sql

package db

import (
	"context"
	"database/sql"
)

const addFederatedBlobURL = `-- name: AddFederatedBlobURL :one

INSERT INTO federated_blob_urls (blob_hash, url, server_id, priority, healthy, created_at)
VALUES ($1, $2, $3, $4, TRUE, $5)
ON CONFLICT (blob_hash, url) DO UPDATE SET
    server_id = COALESCE(excluded.server_id, federated_blob_urls.server_id),
    healthy = federated_blob_urls.healthy
RETURNING id, blob_hash, url, server_id, priority, healthy, last_check, created_at
`

type AddFederatedBlobURLParams struct {
	BlobHash  string
	Url       string
	ServerID  sql.NullString
	Priority  int32
	CreatedAt int64
}

// Federated blob URLs queries
func (q *Queries) AddFederatedBlobURL(ctx context.Context, arg AddFederatedBlobURLParams) (FederatedBlobUrl, error) {
	row := q.db.QueryRowContext(ctx, addFederatedBlobURL,
		arg.BlobHash,
		arg.Url,
		arg.ServerID,
		arg.Priority,
		arg.CreatedAt,
	)
	var i FederatedBlobUrl
	err := row.Scan(
		&i.ID,
		&i.BlobHash,
		&i.Url,
		&i.ServerID,
		&i.Priority,
		&i.Healthy,
		&i.LastCheck,
		&i.CreatedAt,
	)
	return i, err
}

const countFederatedBlobs = `-- name: CountFederatedBlobs :one
SELECT COUNT(*) as count
FROM federated_blobs
`

func (q *Queries) CountFederatedBlobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFederatedBlobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFederatedBlobsByStatus = `-- name: CountFederatedBlobsByStatus :one
SELECT COUNT(*) as count
FROM federated_blobs
WHERE status = $1
`

func (q *Queries) CountFederatedBlobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFederatedBlobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFederatedUsers = `-- name: CountFederatedUsers :one
SELECT COUNT(*) as count
FROM federated_users
`

func (q *Queries) CountFederatedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFederatedUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFederationEventsByStatus = `-- name: CountFederationEventsByStatus :one
SELECT COUNT(*) as count
FROM federation_events
WHERE direction = $1 AND status = $2
`

type CountFederationEventsByStatusParams struct {
	Direction string
	Status    string
}

func (q *Queries) CountFederationEventsByStatus(ctx context.Context, arg CountFederationEventsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFederationEventsByStatus, arg.Direction, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHealthyServers = `-- name: CountHealthyServers :one
SELECT COUNT(*) as count
FROM known_servers
WHERE healthy = TRUE
`

func (q *Queries) CountHealthyServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHealthyServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnownServers = `-- name: CountKnownServers :one
SELECT COUNT(*) as count
FROM known_servers
`

func (q *Queries) CountKnownServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKnownServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithServer = `-- name: CountUsersWithServer :one
SELECT COUNT(DISTINCT pubkey) as count
FROM user_server_lists
WHERE server_url = $1
`

func (q *Queries) CountUsersWithServer(ctx context.Context, serverUrl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersWithServer, serverUrl)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFederationEvent = `-- name: CreateFederationEvent :one

INSERT INTO federation_events (id, event_kind, pubkey, blob_hash, direction, status, relay_url, created_at)
VALUES ($1, $2, $3, $4, $5, 'pending', $6, $7)
RETURNING id, event_id, event_kind, pubkey, blob_hash, direction, status, error, relay_url, created_at, published_at, retries
`

type CreateFederationEventParams struct {
	ID        string
	EventKind int32
	Pubkey    string
	BlobHash  sql.NullString
	Direction string
	RelayUrl  sql.NullString
	CreatedAt int64
}

// Federation events queries
func (q *Queries) CreateFederationEvent(ctx context.Context, arg CreateFederationEventParams) (FederationEvent, error) {
	row := q.db.QueryRowContext(ctx, createFederationEvent,
		arg.ID,
		arg.EventKind,
		arg.Pubkey,
		arg.BlobHash,
		arg.Direction,
		arg.RelayUrl,
		arg.CreatedAt,
	)
	var i FederationEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventKind,
		&i.Pubkey,
		&i.BlobHash,
		&i.Direction,
		&i.Status,
		&i.Error,
		&i.RelayUrl,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Retries,
	)
	return i, err
}

const deleteFederatedBlobURLs = `-- name: DeleteFederatedBlobURLs :exec
DELETE FROM federated_blob_urls
WHERE blob_hash = $1
`

func (q *Queries) DeleteFederatedBlobURLs(ctx context.Context, blobHash string) error {
	_, err := q.db.ExecContext(ctx, deleteFederatedBlobURLs, blobHash)
	return err
}

const deleteFederatedUser = `-- name: DeleteFederatedUser :exec
DELETE FROM federated_users
WHERE pubkey = $1
`

func (q *Queries) DeleteFederatedUser(ctx context.Context, pubkey string) error {
	_, err := q.db.ExecContext(ctx, deleteFederatedUser, pubkey)
	return err
}

const deleteUserServerList = `-- name: DeleteUserServerList :exec
DELETE FROM user_server_lists
WHERE pubkey = $1
`

func (q *Queries) DeleteUserServerList(ctx context.Context, pubkey string) error {
	_, err := q.db.ExecContext(ctx, deleteUserServerList, pubkey)
	return err
}

const getAllFederatedBlobURLs = `-- name: GetAllFederatedBlobURLs :many
SELECT id, blob_hash, url, server_id, priority, healthy, last_check, created_at
FROM federated_blob_urls
WHERE blob_hash = $1
ORDER BY priority ASC
`

func (q *Queries) GetAllFederatedBlobURLs(ctx context.Context, blobHash string) ([]FederatedBlobUrl, error) {
	rows, err := q.db.QueryContext(ctx, getAllFederatedBlobURLs, blobHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederatedBlobUrl
	for rows.Next() {
		var i FederatedBlobUrl
		if err := rows.Scan(
			&i.ID,
			&i.BlobHash,
			&i.Url,
			&i.ServerID,
			&i.Priority,
			&i.Healthy,
			&i.LastCheck,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFederatedBlob = `-- name: GetFederatedBlob :one
SELECT hash, size, mime_type, ref_count, status, discovered_at, mirrored_at, last_seen_at
FROM federated_blobs
WHERE hash = $1
LIMIT 1
`

func (q *Queries) GetFederatedBlob(ctx context.Context, hash string) (FederatedBlob, error) {
	row := q.db.QueryRowContext(ctx, getFederatedBlob, hash)
	var i FederatedBlob
	err := row.Scan(
		&i.Hash,
		&i.Size,
		&i.MimeType,
		&i.RefCount,
		&i.Status,
		&i.DiscoveredAt,
		&i.MirroredAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getFederatedBlobURLs = `-- name: GetFederatedBlobURLs :many
SELECT id, blob_hash, url, server_id, priority, healthy, last_check, created_at
FROM federated_blob_urls
WHERE blob_hash = $1 AND healthy = TRUE
ORDER BY priority ASC
`

func (q *Queries) GetFederatedBlobURLs(ctx context.Context, blobHash string) ([]FederatedBlobUrl, error) {
	rows, err := q.db.QueryContext(ctx, getFederatedBlobURLs, blobHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederatedBlobUrl
	for rows.Next() {
		var i FederatedBlobUrl
		if err := rows.Scan(
			&i.ID,
			&i.BlobHash,
			&i.Url,
			&i.ServerID,
			&i.Priority,
			&i.Healthy,
			&i.LastCheck,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFederatedUser = `-- name: GetFederatedUser :one
SELECT pubkey, event_id, server_rank, created_at, updated_at
FROM federated_users
WHERE pubkey = $1
LIMIT 1
`

func (q *Queries) GetFederatedUser(ctx context.Context, pubkey string) (FederatedUser, error) {
	row := q.db.QueryRowContext(ctx, getFederatedUser, pubkey)
	var i FederatedUser
	err := row.Scan(
		&i.Pubkey,
		&i.EventID,
		&i.ServerRank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFederationEvent = `-- name: GetFederationEvent :one
SELECT id, event_id, event_kind, pubkey, blob_hash, direction, status, error, relay_url, created_at, published_at, retries
FROM federation_events
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFederationEvent(ctx context.Context, id string) (FederationEvent, error) {
	row := q.db.QueryRowContext(ctx, getFederationEvent, id)
	var i FederationEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventKind,
		&i.Pubkey,
		&i.BlobHash,
		&i.Direction,
		&i.Status,
		&i.Error,
		&i.RelayUrl,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Retries,
	)
	return i, err
}

const getFederationEventByNostrID = `-- name: GetFederationEventByNostrID :one
SELECT id, event_id, event_kind, pubkey, blob_hash, direction, status, error, relay_url, created_at, published_at, retries
FROM federation_events
WHERE event_id = $1
LIMIT 1
`

func (q *Queries) GetFederationEventByNostrID(ctx context.Context, eventID sql.NullString) (FederationEvent, error) {
	row := q.db.QueryRowContext(ctx, getFederationEventByNostrID, eventID)
	var i FederationEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventKind,
		&i.Pubkey,
		&i.BlobHash,
		&i.Direction,
		&i.Status,
		&i.Error,
		&i.RelayUrl,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Retries,
	)
	return i, err
}

const getKnownServer = `-- name: GetKnownServer :one
SELECT url, pubkey, user_count, blob_count, healthy, first_seen, last_seen, last_check
FROM known_servers
WHERE url = $1
LIMIT 1
`

func (q *Queries) GetKnownServer(ctx context.Context, url string) (KnownServer, error) {
	row := q.db.QueryRowContext(ctx, getKnownServer, url)
	var i KnownServer
	err := row.Scan(
		&i.Url,
		&i.Pubkey,
		&i.UserCount,
		&i.BlobCount,
		&i.Healthy,
		&i.FirstSeen,
		&i.LastSeen,
		&i.LastCheck,
	)
	return i, err
}

const getUserServerList = `-- name: GetUserServerList :many
SELECT server_url
FROM user_server_lists
WHERE pubkey = $1
ORDER BY rank ASC
`

func (q *Queries) GetUserServerList(ctx context.Context, pubkey string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserServerList, pubkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var server_url string
		if err := rows.Scan(&server_url); err != nil {
			return nil, err
		}
		items = append(items, server_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserServerListFull = `-- name: GetUserServerListFull :many
SELECT pubkey, server_url, rank, event_id, created_at, updated_at
FROM user_server_lists
WHERE pubkey = $1
ORDER BY rank ASC
`

func (q *Queries) GetUserServerListFull(ctx context.Context, pubkey string) ([]UserServerList, error) {
	rows, err := q.db.QueryContext(ctx, getUserServerListFull, pubkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserServerList
	for rows.Next() {
		var i UserServerList
		if err := rows.Scan(
			&i.Pubkey,
			&i.ServerUrl,
			&i.Rank,
			&i.EventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementServerBlobCount = `-- name: IncrementServerBlobCount :exec
UPDATE known_servers
SET blob_count = blob_count + 1, last_seen = $2
WHERE url = $1
`

type IncrementServerBlobCountParams struct {
	Url      string
	LastSeen int64
}

func (q *Queries) IncrementServerBlobCount(ctx context.Context, arg IncrementServerBlobCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementServerBlobCount, arg.Url, arg.LastSeen)
	return err
}

const listAllFederationEvents = `-- name: ListAllFederationEvents :many
SELECT id, event_id, event_kind, pubkey, blob_hash, direction, status, error, relay_url, created_at, published_at, retries
FROM federation_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllFederationEventsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllFederationEvents(ctx context.Context, arg ListAllFederationEventsParams) ([]FederationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAllFederationEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationEvent
	for rows.Next() {
		var i FederationEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventKind,
			&i.Pubkey,
			&i.BlobHash,
			&i.Direction,
			&i.Status,
			&i.Error,
			&i.RelayUrl,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Retries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFederatedBlobsByStatus = `-- name: ListFederatedBlobsByStatus :many
SELECT hash, size, mime_type, ref_count, status, discovered_at, mirrored_at, last_seen_at
FROM federated_blobs
WHERE status = $1
ORDER BY discovered_at DESC
LIMIT $2 OFFSET $3
`

type ListFederatedBlobsByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListFederatedBlobsByStatus(ctx context.Context, arg ListFederatedBlobsByStatusParams) ([]FederatedBlob, error) {
	rows, err := q.db.QueryContext(ctx, listFederatedBlobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederatedBlob
	for rows.Next() {
		var i FederatedBlob
		if err := rows.Scan(
			&i.Hash,
			&i.Size,
			&i.MimeType,
			&i.RefCount,
			&i.Status,
			&i.DiscoveredAt,
			&i.MirroredAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFederatedBlobsForMirroring = `-- name: ListFederatedBlobsForMirroring :many
SELECT hash, size, mime_type, ref_count, status, discovered_at, mirrored_at, last_seen_at
FROM federated_blobs
WHERE status = 'discovered' AND ref_count >= $1
ORDER BY ref_count DESC, discovered_at ASC
LIMIT $2
`

type ListFederatedBlobsForMirroringParams struct {
	RefCount int32
	Limit    int32
}

func (q *Queries) ListFederatedBlobsForMirroring(ctx context.Context, arg ListFederatedBlobsForMirroringParams) ([]FederatedBlob, error) {
	rows, err := q.db.QueryContext(ctx, listFederatedBlobsForMirroring, arg.RefCount, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederatedBlob
	for rows.Next() {
		var i FederatedBlob
		if err := rows.Scan(
			&i.Hash,
			&i.Size,
			&i.MimeType,
			&i.RefCount,
			&i.Status,
			&i.DiscoveredAt,
			&i.MirroredAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFederatedUsers = `-- name: ListFederatedUsers :many
SELECT pubkey, event_id, server_rank, created_at, updated_at
FROM federated_users
ORDER BY server_rank ASC, updated_at DESC
LIMIT $1 OFFSET $2
`

type ListFederatedUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListFederatedUsers(ctx context.Context, arg ListFederatedUsersParams) ([]FederatedUser, error) {
	rows, err := q.db.QueryContext(ctx, listFederatedUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederatedUser
	for rows.Next() {
		var i FederatedUser
		if err := rows.Scan(
			&i.Pubkey,
			&i.EventID,
			&i.ServerRank,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFederationEvents = `-- name: ListFederationEvents :many
SELECT id, event_id, event_kind, pubkey, blob_hash, direction, status, error, relay_url, created_at, published_at, retries
FROM federation_events
WHERE direction = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFederationEventsParams struct {
	Direction string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListFederationEvents(ctx context.Context, arg ListFederationEventsParams) ([]FederationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listFederationEvents, arg.Direction, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationEvent
	for rows.Next() {
		var i FederationEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventKind,
			&i.Pubkey,
			&i.BlobHash,
			&i.Direction,
			&i.Status,
			&i.Error,
			&i.RelayUrl,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Retries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHealthyServers = `-- name: ListHealthyServers :many
SELECT url, pubkey, user_count, blob_count, healthy, first_seen, last_seen, last_check
FROM known_servers
WHERE healthy = TRUE
ORDER BY user_count DESC, last_seen DESC
`

func (q *Queries) ListHealthyServers(ctx context.Context) ([]KnownServer, error) {
	rows, err := q.db.QueryContext(ctx, listHealthyServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnownServer
	for rows.Next() {
		var i KnownServer
		if err := rows.Scan(
			&i.Url,
			&i.Pubkey,
			&i.UserCount,
			&i.BlobCount,
			&i.Healthy,
			&i.FirstSeen,
			&i.LastSeen,
			&i.LastCheck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnownServers = `-- name: ListKnownServers :many
SELECT url, pubkey, user_count, blob_count, healthy, first_seen, last_seen, last_check
FROM known_servers
ORDER BY user_count DESC, last_seen DESC
LIMIT $1 OFFSET $2
`

type ListKnownServersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListKnownServers(ctx context.Context, arg ListKnownServersParams) ([]KnownServer, error) {
	rows, err := q.db.QueryContext(ctx, listKnownServers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnownServer
	for rows.Next() {
		var i KnownServer
		if err := rows.Scan(
			&i.Url,
			&i.Pubkey,
			&i.UserCount,
			&i.BlobCount,
			&i.Healthy,
			&i.FirstSeen,
			&i.LastSeen,
			&i.LastCheck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPublishes = `-- name: ListPendingPublishes :many
SELECT id, event_id, event_kind, pubkey, blob_hash, direction, status, error, relay_url, created_at, published_at, retries
FROM federation_events
WHERE direction = 'publish' AND status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingPublishes(ctx context.Context, limit int32) ([]FederationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPublishes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationEvent
	for rows.Next() {
		var i FederationEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventKind,
			&i.Pubkey,
			&i.BlobHash,
			&i.Direction,
			&i.Status,
			&i.Error,
			&i.RelayUrl,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Retries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFederatedBlobStatus = `-- name: UpdateFederatedBlobStatus :exec
UPDATE federated_blobs
SET status = $2, mirrored_at = $3
WHERE hash = $1
`

type UpdateFederatedBlobStatusParams struct {
	Hash       string
	Status     string
	MirroredAt sql.NullInt64
}

func (q *Queries) UpdateFederatedBlobStatus(ctx context.Context, arg UpdateFederatedBlobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFederatedBlobStatus, arg.Hash, arg.Status, arg.MirroredAt)
	return err
}

const updateFederatedBlobURLHealth = `-- name: UpdateFederatedBlobURLHealth :exec
UPDATE federated_blob_urls
SET healthy = $2, last_check = $3
WHERE id = $1
`

type UpdateFederatedBlobURLHealthParams struct {
	ID        int32
	Healthy   bool
	LastCheck sql.NullInt64
}

func (q *Queries) UpdateFederatedBlobURLHealth(ctx context.Context, arg UpdateFederatedBlobURLHealthParams) error {
	_, err := q.db.ExecContext(ctx, updateFederatedBlobURLHealth, arg.ID, arg.Healthy, arg.LastCheck)
	return err
}

const updateFederationEventStatus = `-- name: UpdateFederationEventStatus :exec
UPDATE federation_events
SET status = $2, event_id = $3, published_at = $4, error = $5, retries = retries + 1
WHERE id = $1
`

type UpdateFederationEventStatusParams struct {
	ID          string
	Status      string
	EventID     sql.NullString
	PublishedAt sql.NullInt64
	Error       sql.NullString
}

func (q *Queries) UpdateFederationEventStatus(ctx context.Context, arg UpdateFederationEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFederationEventStatus,
		arg.ID,
		arg.Status,
		arg.EventID,
		arg.PublishedAt,
		arg.Error,
	)
	return err
}

const updateServerHealth = `-- name: UpdateServerHealth :exec
UPDATE known_servers
SET healthy = $2, last_check = $3
WHERE url = $1
`

type UpdateServerHealthParams struct {
	Url       string
	Healthy   bool
	LastCheck sql.NullInt64
}

func (q *Queries) UpdateServerHealth(ctx context.Context, arg UpdateServerHealthParams) error {
	_, err := q.db.ExecContext(ctx, updateServerHealth, arg.Url, arg.Healthy, arg.LastCheck)
	return err
}

const upsertFederatedBlob = `-- name: UpsertFederatedBlob :one

INSERT INTO federated_blobs (hash, size, mime_type, ref_count, status, discovered_at, last_seen_at)
VALUES ($1, $2, $3, 1, 'discovered', $4, $4)
ON CONFLICT (hash) DO UPDATE SET
    ref_count = federated_blobs.ref_count + 1,
    last_seen_at = excluded.last_seen_at
RETURNING hash, size, mime_type, ref_count, status, discovered_at, mirrored_at, last_seen_at
`

type UpsertFederatedBlobParams struct {
	Hash         string
	Size         int64
	MimeType     string
	DiscoveredAt int64
}

// Federated blobs queries
func (q *Queries) UpsertFederatedBlob(ctx context.Context, arg UpsertFederatedBlobParams) (FederatedBlob, error) {
	row := q.db.QueryRowContext(ctx, upsertFederatedBlob,
		arg.Hash,
		arg.Size,
		arg.MimeType,
		arg.DiscoveredAt,
	)
	var i FederatedBlob
	err := row.Scan(
		&i.Hash,
		&i.Size,
		&i.MimeType,
		&i.RefCount,
		&i.Status,
		&i.DiscoveredAt,
		&i.MirroredAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertFederatedUser = `-- name: UpsertFederatedUser :one

INSERT INTO federated_users (pubkey, event_id, server_rank, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (pubkey) DO UPDATE SET
    event_id = excluded.event_id,
    server_rank = excluded.server_rank,
    updated_at = excluded.updated_at
RETURNING pubkey, event_id, server_rank, created_at, updated_at
`

type UpsertFederatedUserParams struct {
	Pubkey     string
	EventID    string
	ServerRank int32
	CreatedAt  int64
}

// Federated users queries
func (q *Queries) UpsertFederatedUser(ctx context.Context, arg UpsertFederatedUserParams) (FederatedUser, error) {
	row := q.db.QueryRowContext(ctx, upsertFederatedUser,
		arg.Pubkey,
		arg.EventID,
		arg.ServerRank,
		arg.CreatedAt,
	)
	var i FederatedUser
	err := row.Scan(
		&i.Pubkey,
		&i.EventID,
		&i.ServerRank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKnownServer = `-- name: UpsertKnownServer :one

INSERT INTO known_servers (url, pubkey, user_count, blob_count, healthy, first_seen, last_seen)
VALUES ($1, $2, 1, 0, TRUE, $3, $3)
ON CONFLICT (url) DO UPDATE SET
    pubkey = COALESCE(excluded.pubkey, known_servers.pubkey),
    user_count = known_servers.user_count + 1,
    last_seen = excluded.last_seen
RETURNING url, pubkey, user_count, blob_count, healthy, first_seen, last_seen, last_check
`

type UpsertKnownServerParams struct {
	Url       string
	Pubkey    sql.NullString
	FirstSeen int64
}

// Known servers queries
func (q *Queries) UpsertKnownServer(ctx context.Context, arg UpsertKnownServerParams) (KnownServer, error) {
	row := q.db.QueryRowContext(ctx, upsertKnownServer, arg.Url, arg.Pubkey, arg.FirstSeen)
	var i KnownServer
	err := row.Scan(
		&i.Url,
		&i.Pubkey,
		&i.UserCount,
		&i.BlobCount,
		&i.Healthy,
		&i.FirstSeen,
		&i.LastSeen,
		&i.LastCheck,
	)
	return i, err
}

const upsertUserServerList = `-- name: UpsertUserServerList :exec

INSERT INTO user_server_lists (pubkey, server_url, rank, event_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT (pubkey, server_url) DO UPDATE SET
    rank = excluded.rank,
    event_id = excluded.event_id,
    updated_at = excluded.updated_at
`

type UpsertUserServerListParams struct {
	Pubkey    string
	ServerUrl string
	Rank      int32
	EventID   string
	CreatedAt int64
}

// BUD-03: User server list queries
func (q *Queries) UpsertUserServerList(ctx context.Context, arg UpsertUserServerListParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserServerList,
		arg.Pubkey,
		arg.ServerUrl,
		arg.Rank,
		arg.EventID,
		arg.CreatedAt,
	)
	return err
}
