// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gc.sql

package db

import (
	"context"
)

const countOwnerlessBlobs = `-- name: CountOwnerlessBlobs :one
SELECT COUNT(*) AS count
FROM blobs b
WHERE NOT EXISTS (
    SELECT 1 FROM blob_references br WHERE br.hash = b.hash
)
`

func (q *Queries) CountOwnerlessBlobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerlessBlobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countZeroRefBlobs = `-- name: CountZeroRefBlobs :one

SELECT COUNT(*) AS count
FROM blobs
WHERE ref_count <= 0
`

// Garbage-collection / reconciliation queries.
//
// These surface blobs whose reference bookkeeping has drifted from reality:
//   - zero-ref blobs   -- ref_count has been driven to 0 or below but the
//     blobs row still exists (e.g. a crash between
//     DecrementBlobRefCount and DeleteFromHash).
//   - ownerless blobs  -- no blob_references row points at the blob at all.
//     This is the authoritative "no owner" signal and the
//     set the manual reconcile delete targets.
//
// A divergence between the two counts is itself a health signal: it means the
// ref_count column disagrees with the blob_references join table.
func (q *Queries) CountZeroRefBlobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countZeroRefBlobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOwnerlessBlob = `-- name: DeleteOwnerlessBlob :one
DELETE FROM blobs
WHERE blobs.hash = $1
  AND NOT EXISTS (
    SELECT 1 FROM blob_references br WHERE br.hash = blobs.hash
)
RETURNING blobs.hash
`

// Deletes a blob ONLY if it is still ownerless at delete time. The NOT EXISTS
// is re-evaluated atomically within this single statement, closing the TOCTOU
// window between ListOwnerlessBlobs (a snapshot) and the delete: if a new owner
// re-uploaded matching content in between, the row is skipped (0 rows deleted,
// sql.ErrNoRows) instead of destroying a live blob. Returns the hash on delete.
func (q *Queries) DeleteOwnerlessBlob(ctx context.Context, hash string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteOwnerlessBlob, hash)
	err := row.Scan(&hash)
	return hash, err
}

const listOwnerlessBlobs = `-- name: ListOwnerlessBlobs :many
SELECT b.hash, b.size
FROM blobs b
WHERE NOT EXISTS (
    SELECT 1 FROM blob_references br WHERE br.hash = b.hash
)
ORDER BY b.created ASC
LIMIT $1
`

type ListOwnerlessBlobsRow struct {
	Hash string
	Size int64
}

// Blobs with no owner in blob_references, oldest first. Bounded by $1 so a
// large backlog is drained across multiple reconcile invocations.
func (q *Queries) ListOwnerlessBlobs(ctx context.Context, limit int32) ([]ListOwnerlessBlobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerlessBlobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerlessBlobsRow
	for rows.Next() {
		var i ListOwnerlessBlobsRow
		if err := rows.Scan(&i.Hash, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
