// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_mirror.sql

package db

import (
	"context"
	"database/sql"
)

const countMirroredMedia = `-- name: CountMirroredMedia :one
SELECT COUNT(*) AS count
FROM mirrored_media
WHERE status = 'ok'
`

func (q *Queries) CountMirroredMedia(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMirroredMedia)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMirroredMediaForBlob = `-- name: CountMirroredMediaForBlob :one
SELECT COUNT(*) AS count
FROM mirrored_media
WHERE sha256 = $1
`

// How many mirror entries still point at a blob. Distinct URLs can serve
// byte-identical content, so a blob must not be released until the LAST URL
// referencing it is gone.
func (q *Queries) CountMirroredMediaForBlob(ctx context.Context, sha256 sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMirroredMediaForBlob, sha256)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMirroredMedia = `-- name: DeleteMirroredMedia :exec
DELETE FROM mirrored_media
WHERE url_hash = $1
`

func (q *Queries) DeleteMirroredMedia(ctx context.Context, urlHash string) error {
	_, err := q.db.ExecContext(ctx, deleteMirroredMedia, urlHash)
	return err
}

const deleteStaleMirrorFailures = `-- name: DeleteStaleMirrorFailures :exec
DELETE FROM mirrored_media
WHERE status = $1
  AND fetched_at < $2
`

type DeleteStaleMirrorFailuresParams struct {
	Status    string
	FetchedAt int64
}

// Expires negative-cache rows so a host that comes back, or an object whose
// policy verdict would now differ, is eventually retried rather than being
// refused forever.
func (q *Queries) DeleteStaleMirrorFailures(ctx context.Context, arg DeleteStaleMirrorFailuresParams) error {
	_, err := q.db.ExecContext(ctx, deleteStaleMirrorFailures, arg.Status, arg.FetchedAt)
	return err
}

const getMirroredMedia = `-- name: GetMirroredMedia :one

SELECT url_hash, source_url, status, reason, sha256, size, mime, fetched_at, accessed_at
FROM mirrored_media
WHERE url_hash = $1
`

// Remote media mirror queries.
//
// Note what is absent: there is no query here that takes a pubkey, an IP, or
// any other caller identity, because no such column exists. The mirror caches
// content by URL and cannot answer "who viewed this" even if asked. That is
// the point of the feature, so keep it that way.
func (q *Queries) GetMirroredMedia(ctx context.Context, urlHash string) (MirroredMedium, error) {
	row := q.db.QueryRowContext(ctx, getMirroredMedia, urlHash)
	var i MirroredMedium
	err := row.Scan(
		&i.UrlHash,
		&i.SourceUrl,
		&i.Status,
		&i.Reason,
		&i.Sha256,
		&i.Size,
		&i.Mime,
		&i.FetchedAt,
		&i.AccessedAt,
	)
	return i, err
}

const listMirroredMediaLRU = `-- name: ListMirroredMediaLRU :many
SELECT url_hash, sha256, size
FROM mirrored_media
WHERE status = 'ok'
ORDER BY accessed_at ASC, fetched_at ASC
LIMIT $1
`

type ListMirroredMediaLRURow struct {
	UrlHash string
	Sha256  sql.NullString
	Size    int64
}

// Eviction candidates, least recently accessed first. Bounded by $1 so one
// pass cannot stall on a huge cache.
func (q *Queries) ListMirroredMediaLRU(ctx context.Context, limit int32) ([]ListMirroredMediaLRURow, error) {
	rows, err := q.db.QueryContext(ctx, listMirroredMediaLRU, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMirroredMediaLRURow
	for rows.Next() {
		var i ListMirroredMediaLRURow
		if err := rows.Scan(&i.UrlHash, &i.Sha256, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMirroredMediaSize = `-- name: SumMirroredMediaSize :one
SELECT CAST(COALESCE(SUM(size), 0) AS BIGINT) AS total
FROM mirrored_media
WHERE status = 'ok'
`

// Total bytes held by successfully mirrored objects. Failure rows are excluded
// because they hold no bytes.
// CAST(... AS BIGINT), not Postgres's ::BIGINT shorthand: the same generated
// SQL runs against SQLite on self-hosted deployments, and ::  is a syntax
// error there. Without a cast at all, Postgres types SUM(BIGINT) as NUMERIC
// and sqlc emits interface{}.
func (q *Queries) SumMirroredMediaSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumMirroredMediaSize)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const touchMirroredMedia = `-- name: TouchMirroredMedia :exec
UPDATE mirrored_media
SET accessed_at = $2
WHERE url_hash = $1
  AND accessed_at < $2
`

type TouchMirroredMediaParams struct {
	UrlHash    string
	AccessedAt int64
}

// Refreshes the LRU timestamp. Guarded by accessed_at < $2 so a hot object
// costs one write per coarse interval instead of one per request -- which
// keeps write load off a small server and stops the column from becoming a
// fine-grained record of when content was viewed.
func (q *Queries) TouchMirroredMedia(ctx context.Context, arg TouchMirroredMediaParams) error {
	_, err := q.db.ExecContext(ctx, touchMirroredMedia, arg.UrlHash, arg.AccessedAt)
	return err
}

const upsertMirroredMedia = `-- name: UpsertMirroredMedia :exec
INSERT INTO mirrored_media (
    url_hash, source_url, status, reason, sha256, size, mime, fetched_at, accessed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (url_hash) DO UPDATE SET
    source_url  = excluded.source_url,
    status      = excluded.status,
    reason      = excluded.reason,
    sha256      = excluded.sha256,
    size        = excluded.size,
    mime        = excluded.mime,
    fetched_at  = excluded.fetched_at,
    accessed_at = excluded.accessed_at
`

type UpsertMirroredMediaParams struct {
	UrlHash    string
	SourceUrl  string
	Status     string
	Reason     sql.NullString
	Sha256     sql.NullString
	Size       int64
	Mime       sql.NullString
	FetchedAt  int64
	AccessedAt int64
}

// Records the outcome of a fetch, successful or not. Upsert rather than insert
// because a previously unreachable host coming back, or a refused object whose
// policy verdict changed, must overwrite the stale verdict in place.
func (q *Queries) UpsertMirroredMedia(ctx context.Context, arg UpsertMirroredMediaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMirroredMedia,
		arg.UrlHash,
		arg.SourceUrl,
		arg.Status,
		arg.Reason,
		arg.Sha256,
		arg.Size,
		arg.Mime,
		arg.FetchedAt,
		arg.AccessedAt,
	)
	return err
}
