// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Blob struct {
	Pubkey  string
	Hash    string
	Type    string
	Size    int64
	Blob    []byte
	Created int64
}

type MimeType struct {
	Extension string
	MimeType  string
}

type User struct {
	Pubkey     string
	QuotaBytes int64
	UsedBytes  int64
	IsBanned   bool
	CreatedAt  int64
	UpdatedAt  int64
}
