// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Blob struct {
	Pubkey          string
	Hash            string
	Type            string
	Size            int64
	Blob            []byte
	Created         int64
	EncryptionMode  string
	EncryptedDek    sql.NullString
	EncryptionNonce sql.NullString
	OriginalSize    sql.NullInt64
	RefCount        int32
	ExpiresAt       sql.NullInt64
}

type BlobReference struct {
	Pubkey  string
	Hash    string
	Created int64
}

type Blocklist struct {
	Pubkey    string
	Reason    string
	BlockedBy string
	CreatedAt int64
}

type ExpirationPolicy struct {
	ID         int32
	Name       string
	MimePrefix sql.NullString
	TtlSeconds int32
	MaxSize    sql.NullInt64
	Pubkey     sql.NullString
	Priority   int32
	Enabled    bool
	CreatedAt  int64
	UpdatedAt  int64
}

type MimeType struct {
	Extension string
	MimeType  string
}

type RemovedBlob struct {
	Hash      string
	Reason    string
	RemovedBy string
	ReportID  sql.NullInt32
	CreatedAt int64
}

type Report struct {
	ID             int32
	ReporterPubkey sql.NullString
	BlobHash       string
	BlobUrl        string
	Reason         string
	Details        sql.NullString
	Status         string
	ActionTaken    sql.NullString
	ReviewedBy     sql.NullString
	CreatedAt      int64
	ReviewedAt     sql.NullInt64
}

type TransparencyStat struct {
	ID               int32
	TotalReports     int64
	ReportsActioned  int64
	ReportsDismissed int64
	BlobsRemoved     int64
	UsersBanned      int64
	LastUpdated      int64
}

type UploadChunk struct {
	SessionID   string
	ChunkNum    int32
	Size        int64
	OffsetBytes int64
	Hash        string
	ReceivedAt  int64
}

type UploadSession struct {
	ID             string
	Pubkey         string
	Hash           sql.NullString
	TotalSize      int64
	ChunkSize      int64
	MimeType       sql.NullString
	ChunksReceived int32
	BytesReceived  int64
	Status         string
	EncryptionMode string
	Created        int64
	Updated        int64
	ExpiresAt      int64
}

type User struct {
	Pubkey     string
	QuotaBytes int64
	UsedBytes  int64
	IsBanned   bool
	CreatedAt  int64
	UpdatedAt  int64
}
