// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"
)

const createPaymentRequest = `-- name: CreatePaymentRequest :one

INSERT INTO payment_requests (
    id, pubkey, amount_sats, bytes_requested,
    lightning_invoice, cashu_request, payment_hash,
    status, created_at, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', $8, $9)
RETURNING id, pubkey, amount_sats, bytes_requested, lightning_invoice, cashu_request, payment_hash, status, created_at, expires_at, paid_at, proof_data
`

type CreatePaymentRequestParams struct {
	ID               string
	Pubkey           string
	AmountSats       int64
	BytesRequested   int64
	LightningInvoice sql.NullString
	CashuRequest     sql.NullString
	PaymentHash      sql.NullString
	CreatedAt        int64
	ExpiresAt        int64
}

// Payment queries for BUD-07 support
func (q *Queries) CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (PaymentRequest, error) {
	row := q.db.QueryRowContext(ctx, createPaymentRequest,
		arg.ID,
		arg.Pubkey,
		arg.AmountSats,
		arg.BytesRequested,
		arg.LightningInvoice,
		arg.CashuRequest,
		arg.PaymentHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.AmountSats,
		&i.BytesRequested,
		&i.LightningInvoice,
		&i.CashuRequest,
		&i.PaymentHash,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ProofData,
	)
	return i, err
}

const expirePendingPayments = `-- name: ExpirePendingPayments :exec
UPDATE payment_requests
SET status = 'expired'
WHERE status = 'pending' AND expires_at < $1
`

// Batch expire all pending payments past their expiry time
func (q *Queries) ExpirePendingPayments(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, expirePendingPayments, expiresAt)
	return err
}

const getPaymentRequest = `-- name: GetPaymentRequest :one
SELECT id, pubkey, amount_sats, bytes_requested, lightning_invoice, cashu_request, payment_hash, status, created_at, expires_at, paid_at, proof_data
FROM payment_requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPaymentRequest(ctx context.Context, id string) (PaymentRequest, error) {
	row := q.db.QueryRowContext(ctx, getPaymentRequest, id)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.AmountSats,
		&i.BytesRequested,
		&i.LightningInvoice,
		&i.CashuRequest,
		&i.PaymentHash,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ProofData,
	)
	return i, err
}

const getPaymentRequestByHash = `-- name: GetPaymentRequestByHash :one
SELECT id, pubkey, amount_sats, bytes_requested, lightning_invoice, cashu_request, payment_hash, status, created_at, expires_at, paid_at, proof_data
FROM payment_requests
WHERE payment_hash = $1
LIMIT 1
`

func (q *Queries) GetPaymentRequestByHash(ctx context.Context, paymentHash sql.NullString) (PaymentRequest, error) {
	row := q.db.QueryRowContext(ctx, getPaymentRequestByHash, paymentHash)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.AmountSats,
		&i.BytesRequested,
		&i.LightningInvoice,
		&i.CashuRequest,
		&i.PaymentHash,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ProofData,
	)
	return i, err
}

const getPaymentStats = `-- name: GetPaymentStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'paid') AS total_paid,
    COUNT(*) FILTER (WHERE status = 'pending') AS total_pending,
    COUNT(*) FILTER (WHERE status = 'expired') AS total_expired,
    COALESCE(SUM(amount_sats) FILTER (WHERE status = 'paid'), 0) AS total_sats_received,
    COALESCE(SUM(bytes_requested) FILTER (WHERE status = 'paid'), 0) AS total_bytes_paid
FROM payment_requests
`

type GetPaymentStatsRow struct {
	TotalPaid         int64
	TotalPending      int64
	TotalExpired      int64
	TotalSatsReceived interface{}
	TotalBytesPaid    interface{}
}

// Get payment statistics for admin dashboard
func (q *Queries) GetPaymentStats(ctx context.Context) (GetPaymentStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentStats)
	var i GetPaymentStatsRow
	err := row.Scan(
		&i.TotalPaid,
		&i.TotalPending,
		&i.TotalExpired,
		&i.TotalSatsReceived,
		&i.TotalBytesPaid,
	)
	return i, err
}

const getPendingPaymentRequests = `-- name: GetPendingPaymentRequests :many
SELECT id, pubkey, amount_sats, bytes_requested, lightning_invoice, cashu_request, payment_hash, status, created_at, expires_at, paid_at, proof_data
FROM payment_requests
WHERE pubkey = $1 AND status = 'pending' AND expires_at > $2
ORDER BY created_at DESC
`

type GetPendingPaymentRequestsParams struct {
	Pubkey    string
	ExpiresAt int64
}

func (q *Queries) GetPendingPaymentRequests(ctx context.Context, arg GetPendingPaymentRequestsParams) ([]PaymentRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingPaymentRequests, arg.Pubkey, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentRequest
	for rows.Next() {
		var i PaymentRequest
		if err := rows.Scan(
			&i.ID,
			&i.Pubkey,
			&i.AmountSats,
			&i.BytesRequested,
			&i.LightningInvoice,
			&i.CashuRequest,
			&i.PaymentHash,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.ProofData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPayments = `-- name: GetRecentPayments :many
SELECT id, pubkey, amount_sats, bytes_requested, lightning_invoice, cashu_request, payment_hash, status, created_at, expires_at, paid_at, proof_data
FROM payment_requests
WHERE status = 'paid'
ORDER BY paid_at DESC
LIMIT $1
`

// Get recent payments for admin view
func (q *Queries) GetRecentPayments(ctx context.Context, limit int32) ([]PaymentRequest, error) {
	rows, err := q.db.QueryContext(ctx, getRecentPayments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentRequest
	for rows.Next() {
		var i PaymentRequest
		if err := rows.Scan(
			&i.ID,
			&i.Pubkey,
			&i.AmountSats,
			&i.BytesRequested,
			&i.LightningInvoice,
			&i.CashuRequest,
			&i.PaymentHash,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.ProofData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFreeBytesUsed = `-- name: GetUserFreeBytesUsed :one
SELECT free_bytes_used, free_bytes_limit
FROM users
WHERE pubkey = $1
LIMIT 1
`

type GetUserFreeBytesUsedRow struct {
	FreeBytesUsed  int64
	FreeBytesLimit int64
}

func (q *Queries) GetUserFreeBytesUsed(ctx context.Context, pubkey string) (GetUserFreeBytesUsedRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFreeBytesUsed, pubkey)
	var i GetUserFreeBytesUsedRow
	err := row.Scan(&i.FreeBytesUsed, &i.FreeBytesLimit)
	return i, err
}

const incrementUserFreeBytesUsed = `-- name: IncrementUserFreeBytesUsed :exec
UPDATE users
SET free_bytes_used = free_bytes_used + $1, updated_at = $2
WHERE pubkey = $3
`

type IncrementUserFreeBytesUsedParams struct {
	FreeBytesUsed int64
	UpdatedAt     int64
	Pubkey        string
}

func (q *Queries) IncrementUserFreeBytesUsed(ctx context.Context, arg IncrementUserFreeBytesUsedParams) error {
	_, err := q.db.ExecContext(ctx, incrementUserFreeBytesUsed, arg.FreeBytesUsed, arg.UpdatedAt, arg.Pubkey)
	return err
}

const markPaymentExpired = `-- name: MarkPaymentExpired :exec
UPDATE payment_requests
SET status = 'expired'
WHERE id = $1
`

func (q *Queries) MarkPaymentExpired(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markPaymentExpired, id)
	return err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :exec
UPDATE payment_requests
SET status = 'paid', paid_at = $1, proof_data = $2
WHERE id = $3
`

type MarkPaymentPaidParams struct {
	PaidAt    sql.NullInt64
	ProofData sql.NullString
	ID        string
}

func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) error {
	_, err := q.db.ExecContext(ctx, markPaymentPaid, arg.PaidAt, arg.ProofData, arg.ID)
	return err
}

const setUserFreeBytesLimit = `-- name: SetUserFreeBytesLimit :exec
UPDATE users
SET free_bytes_limit = $1, updated_at = $2
WHERE pubkey = $3
`

type SetUserFreeBytesLimitParams struct {
	FreeBytesLimit int64
	UpdatedAt      int64
	Pubkey         string
}

func (q *Queries) SetUserFreeBytesLimit(ctx context.Context, arg SetUserFreeBytesLimitParams) error {
	_, err := q.db.ExecContext(ctx, setUserFreeBytesLimit, arg.FreeBytesLimit, arg.UpdatedAt, arg.Pubkey)
	return err
}

const updateUserFreeBytesUsed = `-- name: UpdateUserFreeBytesUsed :exec
UPDATE users
SET free_bytes_used = $1, updated_at = $2
WHERE pubkey = $3
`

type UpdateUserFreeBytesUsedParams struct {
	FreeBytesUsed int64
	UpdatedAt     int64
	Pubkey        string
}

func (q *Queries) UpdateUserFreeBytesUsed(ctx context.Context, arg UpdateUserFreeBytesUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFreeBytesUsed, arg.FreeBytesUsed, arg.UpdatedAt, arg.Pubkey)
	return err
}
