// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: removed_blobs.sql

package db

import (
	"context"
	"database/sql"
)

const addRemovedBlob = `-- name: AddRemovedBlob :exec
INSERT INTO removed_blobs (hash, reason, removed_by, report_id, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (hash) DO UPDATE SET
    reason = excluded.reason,
    removed_by = excluded.removed_by,
    report_id = excluded.report_id,
    created_at = excluded.created_at
`

type AddRemovedBlobParams struct {
	Hash      string
	Reason    string
	RemovedBy string
	ReportID  sql.NullInt32
	CreatedAt int64
}

func (q *Queries) AddRemovedBlob(ctx context.Context, arg AddRemovedBlobParams) error {
	_, err := q.db.ExecContext(ctx, addRemovedBlob,
		arg.Hash,
		arg.Reason,
		arg.RemovedBy,
		arg.ReportID,
		arg.CreatedAt,
	)
	return err
}

const deleteRemovedBlob = `-- name: DeleteRemovedBlob :exec
DELETE FROM removed_blobs
WHERE hash = $1
`

func (q *Queries) DeleteRemovedBlob(ctx context.Context, hash string) error {
	_, err := q.db.ExecContext(ctx, deleteRemovedBlob, hash)
	return err
}

const getRemovedBlob = `-- name: GetRemovedBlob :one
SELECT hash, reason, removed_by, report_id, created_at
FROM removed_blobs
WHERE hash = $1
`

func (q *Queries) GetRemovedBlob(ctx context.Context, hash string) (RemovedBlob, error) {
	row := q.db.QueryRowContext(ctx, getRemovedBlob, hash)
	var i RemovedBlob
	err := row.Scan(
		&i.Hash,
		&i.Reason,
		&i.RemovedBy,
		&i.ReportID,
		&i.CreatedAt,
	)
	return i, err
}

const getRemovedBlobCount = `-- name: GetRemovedBlobCount :one
SELECT COUNT(*) as count
FROM removed_blobs
`

func (q *Queries) GetRemovedBlobCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRemovedBlobCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isHashRemoved = `-- name: IsHashRemoved :one
SELECT EXISTS(
    SELECT 1 FROM removed_blobs WHERE hash = $1
) as removed
`

func (q *Queries) IsHashRemoved(ctx context.Context, hash string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isHashRemoved, hash)
	var removed bool
	err := row.Scan(&removed)
	return removed, err
}

const listRemovedBlobs = `-- name: ListRemovedBlobs :many
SELECT hash, reason, removed_by, report_id, created_at
FROM removed_blobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRemovedBlobsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRemovedBlobs(ctx context.Context, arg ListRemovedBlobsParams) ([]RemovedBlob, error) {
	rows, err := q.db.QueryContext(ctx, listRemovedBlobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemovedBlob
	for rows.Next() {
		var i RemovedBlob
		if err := rows.Scan(
			&i.Hash,
			&i.Reason,
			&i.RemovedBy,
			&i.ReportID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
