// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"
	"database/sql"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_pubkey, blob_hash, blob_url, reason, details, status, created_at)
VALUES ($1, $2, $3, $4, $5, 'pending', $6)
RETURNING id, reporter_pubkey, blob_hash, blob_url, reason, details, status, action_taken, reviewed_by, created_at, reviewed_at
`

type CreateReportParams struct {
	ReporterPubkey sql.NullString
	BlobHash       string
	BlobUrl        string
	Reason         string
	Details        sql.NullString
	CreatedAt      int64
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ReporterPubkey,
		arg.BlobHash,
		arg.BlobUrl,
		arg.Reason,
		arg.Details,
		arg.CreatedAt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterPubkey,
		&i.BlobHash,
		&i.BlobUrl,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.ActionTaken,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getPendingReportCount = `-- name: GetPendingReportCount :one
SELECT COUNT(*) as count
FROM reports
WHERE status = 'pending'
`

func (q *Queries) GetPendingReportCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPendingReportCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReport = `-- name: GetReport :one
SELECT id, reporter_pubkey, blob_hash, blob_url, reason, details, status, action_taken, reviewed_by, created_at, reviewed_at
FROM reports
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetReport(ctx context.Context, id int32) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterPubkey,
		&i.BlobHash,
		&i.BlobUrl,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.ActionTaken,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getReportCountByBlobHash = `-- name: GetReportCountByBlobHash :one
SELECT COUNT(*) as count
FROM reports
WHERE blob_hash = $1
`

func (q *Queries) GetReportCountByBlobHash(ctx context.Context, blobHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReportCountByBlobHash, blobHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReportStats = `-- name: GetReportStats :one
SELECT
    COUNT(*) as total_reports,
    COUNT(*) FILTER (WHERE status = 'actioned') as reports_actioned,
    COUNT(*) FILTER (WHERE status = 'dismissed') as reports_dismissed,
    COUNT(*) FILTER (WHERE action_taken = 'removed') as blobs_removed,
    COUNT(*) FILTER (WHERE action_taken = 'user_banned') as users_banned
FROM reports
`

type GetReportStatsRow struct {
	TotalReports     int64
	ReportsActioned  int64
	ReportsDismissed int64
	BlobsRemoved     int64
	UsersBanned      int64
}

func (q *Queries) GetReportStats(ctx context.Context) (GetReportStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getReportStats)
	var i GetReportStatsRow
	err := row.Scan(
		&i.TotalReports,
		&i.ReportsActioned,
		&i.ReportsDismissed,
		&i.BlobsRemoved,
		&i.UsersBanned,
	)
	return i, err
}

const listAllReports = `-- name: ListAllReports :many
SELECT id, reporter_pubkey, blob_hash, blob_url, reason, details, status, action_taken, reviewed_by, created_at, reviewed_at
FROM reports
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllReportsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllReports(ctx context.Context, arg ListAllReportsParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listAllReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterPubkey,
			&i.BlobHash,
			&i.BlobUrl,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.ActionTaken,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReports = `-- name: ListPendingReports :many
SELECT id, reporter_pubkey, blob_hash, blob_url, reason, details, status, action_taken, reviewed_by, created_at, reviewed_at
FROM reports
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingReportsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPendingReports(ctx context.Context, arg ListPendingReportsParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterPubkey,
			&i.BlobHash,
			&i.BlobUrl,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.ActionTaken,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByBlobHash = `-- name: ListReportsByBlobHash :many
SELECT id, reporter_pubkey, blob_hash, blob_url, reason, details, status, action_taken, reviewed_by, created_at, reviewed_at
FROM reports
WHERE blob_hash = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReportsByBlobHash(ctx context.Context, blobHash string) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByBlobHash, blobHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterPubkey,
			&i.BlobHash,
			&i.BlobUrl,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.ActionTaken,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByStatus = `-- name: ListReportsByStatus :many
SELECT id, reporter_pubkey, blob_hash, blob_url, reason, details, status, action_taken, reviewed_by, created_at, reviewed_at
FROM reports
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReportsByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListReportsByStatus(ctx context.Context, arg ListReportsByStatusParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterPubkey,
			&i.BlobHash,
			&i.BlobUrl,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.ActionTaken,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE reports
SET status = $1, action_taken = $2, reviewed_by = $3, reviewed_at = $4
WHERE id = $5
`

type UpdateReportStatusParams struct {
	Status      string
	ActionTaken sql.NullString
	ReviewedBy  sql.NullString
	ReviewedAt  sql.NullInt64
	ID          int32
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReportStatus,
		arg.Status,
		arg.ActionTaken,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ID,
	)
	return err
}
