// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createUploadChunk = `-- name: CreateUploadChunk :one
INSERT INTO upload_chunks(
  session_id,
  chunk_num,
  size,
  offset_bytes,
  hash,
  received_at
) VALUES ($1,$2,$3,$4,$5,$6)
RETURNING session_id, chunk_num, size, offset_bytes, hash, received_at
`

type CreateUploadChunkParams struct {
	SessionID   string
	ChunkNum    int32
	Size        int64
	OffsetBytes int64
	Hash        string
	ReceivedAt  int64
}

func (q *Queries) CreateUploadChunk(ctx context.Context, arg CreateUploadChunkParams) (UploadChunk, error) {
	row := q.db.QueryRowContext(ctx, createUploadChunk,
		arg.SessionID,
		arg.ChunkNum,
		arg.Size,
		arg.OffsetBytes,
		arg.Hash,
		arg.ReceivedAt,
	)
	var i UploadChunk
	err := row.Scan(
		&i.SessionID,
		&i.ChunkNum,
		&i.Size,
		&i.OffsetBytes,
		&i.Hash,
		&i.ReceivedAt,
	)
	return i, err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO upload_sessions(
  id,
  pubkey,
  hash,
  total_size,
  chunk_size,
  mime_type,
  chunks_received,
  bytes_received,
  status,
  encryption_mode,
  created,
  updated,
  expires_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
RETURNING id, pubkey, hash, total_size, chunk_size, mime_type, chunks_received, bytes_received, status, encryption_mode, created, updated, expires_at
`

type CreateUploadSessionParams struct {
	ID             string
	Pubkey         string
	Hash           sql.NullString
	TotalSize      int64
	ChunkSize      int64
	MimeType       sql.NullString
	ChunksReceived int32
	BytesReceived  int64
	Status         string
	EncryptionMode string
	Created        int64
	Updated        int64
	ExpiresAt      int64
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, createUploadSession,
		arg.ID,
		arg.Pubkey,
		arg.Hash,
		arg.TotalSize,
		arg.ChunkSize,
		arg.MimeType,
		arg.ChunksReceived,
		arg.BytesReceived,
		arg.Status,
		arg.EncryptionMode,
		arg.Created,
		arg.Updated,
		arg.ExpiresAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Hash,
		&i.TotalSize,
		&i.ChunkSize,
		&i.MimeType,
		&i.ChunksReceived,
		&i.BytesReceived,
		&i.Status,
		&i.EncryptionMode,
		&i.Created,
		&i.Updated,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :many
DELETE FROM upload_sessions
WHERE expires_at < $1
RETURNING id
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUploadChunks = `-- name: DeleteUploadChunks :exec
DELETE FROM upload_chunks
WHERE session_id = $1
`

func (q *Queries) DeleteUploadChunks(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteUploadChunks, sessionID)
	return err
}

const deleteUploadSession = `-- name: DeleteUploadSession :exec
DELETE FROM upload_sessions
WHERE id = $1
`

func (q *Queries) DeleteUploadSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUploadSession, id)
	return err
}

const getUploadChunk = `-- name: GetUploadChunk :one
SELECT session_id, chunk_num, size, offset_bytes, hash, received_at
FROM upload_chunks
WHERE session_id = $1 AND chunk_num = $2
LIMIT 1
`

type GetUploadChunkParams struct {
	SessionID string
	ChunkNum  int32
}

func (q *Queries) GetUploadChunk(ctx context.Context, arg GetUploadChunkParams) (UploadChunk, error) {
	row := q.db.QueryRowContext(ctx, getUploadChunk, arg.SessionID, arg.ChunkNum)
	var i UploadChunk
	err := row.Scan(
		&i.SessionID,
		&i.ChunkNum,
		&i.Size,
		&i.OffsetBytes,
		&i.Hash,
		&i.ReceivedAt,
	)
	return i, err
}

const getUploadChunks = `-- name: GetUploadChunks :many
SELECT session_id, chunk_num, size, offset_bytes, hash, received_at
FROM upload_chunks
WHERE session_id = $1
ORDER BY chunk_num
`

func (q *Queries) GetUploadChunks(ctx context.Context, sessionID string) ([]UploadChunk, error) {
	rows, err := q.db.QueryContext(ctx, getUploadChunks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadChunk
	for rows.Next() {
		var i UploadChunk
		if err := rows.Scan(
			&i.SessionID,
			&i.ChunkNum,
			&i.Size,
			&i.OffsetBytes,
			&i.Hash,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, pubkey, hash, total_size, chunk_size, mime_type, chunks_received, bytes_received, status, encryption_mode, created, updated, expires_at
FROM upload_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUploadSession(ctx context.Context, id string) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, getUploadSession, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Hash,
		&i.TotalSize,
		&i.ChunkSize,
		&i.MimeType,
		&i.ChunksReceived,
		&i.BytesReceived,
		&i.Status,
		&i.EncryptionMode,
		&i.Created,
		&i.Updated,
		&i.ExpiresAt,
	)
	return i, err
}

const getUploadSessionsByPubkey = `-- name: GetUploadSessionsByPubkey :many
SELECT id, pubkey, hash, total_size, chunk_size, mime_type, chunks_received, bytes_received, status, encryption_mode, created, updated, expires_at
FROM upload_sessions
WHERE pubkey = $1 AND status = 'active'
ORDER BY created DESC
`

func (q *Queries) GetUploadSessionsByPubkey(ctx context.Context, pubkey string) ([]UploadSession, error) {
	rows, err := q.db.QueryContext(ctx, getUploadSessionsByPubkey, pubkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadSession
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.Pubkey,
			&i.Hash,
			&i.TotalSize,
			&i.ChunkSize,
			&i.MimeType,
			&i.ChunksReceived,
			&i.BytesReceived,
			&i.Status,
			&i.EncryptionMode,
			&i.Created,
			&i.Updated,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadSessionHash = `-- name: UpdateUploadSessionHash :exec
UPDATE upload_sessions
SET hash = $2,
    updated = $3
WHERE id = $1
`

type UpdateUploadSessionHashParams struct {
	ID      string
	Hash    sql.NullString
	Updated int64
}

func (q *Queries) UpdateUploadSessionHash(ctx context.Context, arg UpdateUploadSessionHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadSessionHash, arg.ID, arg.Hash, arg.Updated)
	return err
}

const updateUploadSessionProgress = `-- name: UpdateUploadSessionProgress :exec
UPDATE upload_sessions
SET chunks_received = $2,
    bytes_received = $3,
    updated = $4
WHERE id = $1
`

type UpdateUploadSessionProgressParams struct {
	ID             string
	ChunksReceived int32
	BytesReceived  int64
	Updated        int64
}

func (q *Queries) UpdateUploadSessionProgress(ctx context.Context, arg UpdateUploadSessionProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadSessionProgress,
		arg.ID,
		arg.ChunksReceived,
		arg.BytesReceived,
		arg.Updated,
	)
	return err
}

const updateUploadSessionStatus = `-- name: UpdateUploadSessionStatus :exec
UPDATE upload_sessions
SET status = $2,
    updated = $3
WHERE id = $1
`

type UpdateUploadSessionStatusParams struct {
	ID      string
	Status  string
	Updated int64
}

func (q *Queries) UpdateUploadSessionStatus(ctx context.Context, arg UpdateUploadSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadSessionStatus, arg.ID, arg.Status, arg.Updated)
	return err
}
