// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const banUser = `-- name: BanUser :exec
UPDATE users
SET is_banned = TRUE, updated_at = $1
WHERE pubkey = $2
`

type BanUserParams struct {
	UpdatedAt int64
	Pubkey    string
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.ExecContext(ctx, banUser, arg.UpdatedAt, arg.Pubkey)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (pubkey, quota_bytes, used_bytes, is_banned, created_at, updated_at)
VALUES ($1, $2, 0, FALSE, $3, $4)
RETURNING pubkey, quota_bytes, used_bytes, is_banned, created_at, updated_at
`

type CreateUserParams struct {
	Pubkey     string
	QuotaBytes int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Pubkey,
		arg.QuotaBytes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.Pubkey,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementUserUsage = `-- name: DecrementUserUsage :exec
UPDATE users
SET used_bytes = CASE
    WHEN used_bytes >= $1 THEN used_bytes - $2
    ELSE 0
END, updated_at = $3
WHERE pubkey = $4
`

type DecrementUserUsageParams struct {
	UsedBytes   int64
	UsedBytes_2 int64
	UpdatedAt   int64
	Pubkey      string
}

func (q *Queries) DecrementUserUsage(ctx context.Context, arg DecrementUserUsageParams) error {
	_, err := q.db.ExecContext(ctx, decrementUserUsage,
		arg.UsedBytes,
		arg.UsedBytes_2,
		arg.UpdatedAt,
		arg.Pubkey,
	)
	return err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (pubkey, quota_bytes, used_bytes, is_banned, created_at, updated_at)
VALUES ($1, $2, 0, FALSE, $3, $4)
ON CONFLICT(pubkey) DO UPDATE SET updated_at = excluded.updated_at
RETURNING pubkey, quota_bytes, used_bytes, is_banned, created_at, updated_at
`

type GetOrCreateUserParams struct {
	Pubkey     string
	QuotaBytes int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) GetOrCreateUser(ctx context.Context, arg GetOrCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateUser,
		arg.Pubkey,
		arg.QuotaBytes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.Pubkey,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT pubkey, quota_bytes, used_bytes, is_banned, created_at, updated_at
FROM users
WHERE pubkey = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, pubkey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, pubkey)
	var i User
	err := row.Scan(
		&i.Pubkey,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCount = `-- name: GetUserCount :one
SELECT COUNT(*) as count
FROM users
`

func (q *Queries) GetUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserQuota = `-- name: GetUserQuota :one
SELECT quota_bytes, used_bytes
FROM users
WHERE pubkey = $1
LIMIT 1
`

type GetUserQuotaRow struct {
	QuotaBytes int64
	UsedBytes  int64
}

func (q *Queries) GetUserQuota(ctx context.Context, pubkey string) (GetUserQuotaRow, error) {
	row := q.db.QueryRowContext(ctx, getUserQuota, pubkey)
	var i GetUserQuotaRow
	err := row.Scan(&i.QuotaBytes, &i.UsedBytes)
	return i, err
}

const incrementUserUsage = `-- name: IncrementUserUsage :exec
UPDATE users
SET used_bytes = used_bytes + $1, updated_at = $2
WHERE pubkey = $3
`

type IncrementUserUsageParams struct {
	UsedBytes int64
	UpdatedAt int64
	Pubkey    string
}

func (q *Queries) IncrementUserUsage(ctx context.Context, arg IncrementUserUsageParams) error {
	_, err := q.db.ExecContext(ctx, incrementUserUsage, arg.UsedBytes, arg.UpdatedAt, arg.Pubkey)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT pubkey, quota_bytes, used_bytes, is_banned, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Pubkey,
			&i.QuotaBytes,
			&i.UsedBytes,
			&i.IsBanned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateUserUsage = `-- name: RecalculateUserUsage :exec
UPDATE users
SET used_bytes = (
    SELECT COALESCE(SUM(b.size), 0)
    FROM blobs b
    INNER JOIN blob_references br ON b.hash = br.hash
    WHERE br.pubkey = users.pubkey
), updated_at = $1
WHERE users.pubkey = $2
`

type RecalculateUserUsageParams struct {
	UpdatedAt int64
	Pubkey    string
}

// Recalculate usage based on blob_references table (deduplication-aware)
func (q *Queries) RecalculateUserUsage(ctx context.Context, arg RecalculateUserUsageParams) error {
	_, err := q.db.ExecContext(ctx, recalculateUserUsage, arg.UpdatedAt, arg.Pubkey)
	return err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users
SET is_banned = FALSE, updated_at = $1
WHERE pubkey = $2
`

type UnbanUserParams struct {
	UpdatedAt int64
	Pubkey    string
}

func (q *Queries) UnbanUser(ctx context.Context, arg UnbanUserParams) error {
	_, err := q.db.ExecContext(ctx, unbanUser, arg.UpdatedAt, arg.Pubkey)
	return err
}

const updateUserQuota = `-- name: UpdateUserQuota :exec
UPDATE users
SET quota_bytes = $1, updated_at = $2
WHERE pubkey = $3
`

type UpdateUserQuotaParams struct {
	QuotaBytes int64
	UpdatedAt  int64
	Pubkey     string
}

func (q *Queries) UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error {
	_, err := q.db.ExecContext(ctx, updateUserQuota, arg.QuotaBytes, arg.UpdatedAt, arg.Pubkey)
	return err
}

const updateUserUsage = `-- name: UpdateUserUsage :exec
UPDATE users
SET used_bytes = $1, updated_at = $2
WHERE pubkey = $3
`

type UpdateUserUsageParams struct {
	UsedBytes int64
	UpdatedAt int64
	Pubkey    string
}

func (q *Queries) UpdateUserUsage(ctx context.Context, arg UpdateUserUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateUserUsage, arg.UsedBytes, arg.UpdatedAt, arg.Pubkey)
	return err
}
